apiVersion: v1
kind: ReplicationController
metadata:
  name: en-notifications
  labels:
    name: en-notifications
    version: v1
spec:
  replicas: 1
  selector:
    name: en-notifications
    version: v1
  template:
    metadata:
      labels:
        name: en-notifications
        version: v1
    spec:
      containers:
        - name: en-notifications
          image: eu.gcr.io/eve-notifications/en-notifications:latest
          volumeMounts:
            - name: en-gcm-api
              mountPath: /media/secrets/
          resources:
            limits:
              cpu: "20m"
      volumes:
        - name: en-gcm-api
          secret:
            secretName: en-gcm-api
