apiVersion: v1
kind: Service
metadata:
  name: en-notifications
  labels:
    name: en-notifications
    version: v1
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    name: en-notifications
    version: v1