apiVersion: v1
kind: Service
metadata:
  name: en-api-gateway
  labels:
    name: en-api-gateway
    version: v1
spec:
  externalIPs:
    - 10.240.0.2
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    name: en-api-gateway
    version: v1