apiVersion: v1
kind: ReplicationController
metadata:
  name: en-test
  labels:
    name: en-test
    version: v1
spec:
  replicas: 1
  selector:
    name: en-test
    version: v1
  template:
    metadata:
      labels:
        name: en-test
        version: v1
    spec:
      containers:
        - name: en-test
          image: eu.gcr.io/eve-notifications/en-test:latest
          volumeMounts:
            - name: en-app-credentials
              mountPath: /media/secrets
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /media/secrets/key.json
          ports:
            - name: http
              containerPort: 8000
          resources:
            limits:
              cpu: "20m"
      volumes:
        - name: en-app-credentials
          secret:
            secretName: en-app-credentials