apiVersion: v1
kind: Secret
metadata:
  name: en-rss-setting-nginx-config
data:
  en-rss-settings.conf: c2VydmVyIHsNCiAgICBsaXN0ZW4gODAgZGVmYXVsdF9zZXJ2ZXI7DQoNCiAgICBsb2NhdGlvbiAvIHsNCiAgICAgICAgcHJveHlfc2V0X2hlYWRlciBIT1NUICRob3N0Ow0KICAgICAgICBwcm94eV9zZXRfaGVhZGVyIFgtUmVhbC1JUCAkcmVtb3RlX2FkZHI7DQogICAgICAgIHByb3h5X3NldF9oZWFkZXIgWC1Gb3J3YXJkZWQtUHJvdG8gJHNjaGVtZTsNCiAgICAgICAgcHJveHlfc2V0X2hlYWRlciBYLUZvcndhcmRlZC1Gb3IgJHByb3h5X2FkZF94X2ZvcndhcmRlZF9mb3I7DQogICAgICAgIHByb3h5X3Bhc3MgaHR0cDovLzEyNy4wLjAuMTo4MDAwOw0KICAgIH0NCn0NCg==