apiVersion: v1
kind: Service
metadata:
  name: en-rss-settings
  labels:
    name: en-rss-settings
    version: v1
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    name: en-rss-settings
    version: v1