apiVersion: v1
kind: ReplicationController
metadata:
  name: en-rss-settings
  labels:
    name: en-rss-settings
    version: v1
spec:
  replicas: 1
  selector:
    name: en-rss-settings
    version: v1
  template:
    metadata:
      labels:
        name: en-rss-settings
        version: v1
    spec:
      containers:
        - name: en-rss-settings
          image: eu.gcr.io/eve-notifications/en-rss-settings:latest
          volumeMounts:
            - name: en-rss-secrets
              mountPath: /media/secrets
          resources:
            limits:
              cpu: 50m
          env:
            - name: GCLOUD_DATASET_ID
              value: eve-notifications
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /media/secrets/key.json
      volumes:
        - name: en-rss-secrets
          secret:
            secretName: en-rss-secrets