apiVersion: v1
kind: ReplicationController
metadata:
  name: en-topic-settings
  labels:
    name: en-topic-settings
    version: v1
spec:
  replicas: 1
  selector:
    name: en-topic-settings
    version: v1
  template:
    metadata:
      labels:
        name: en-topic-settings
        version: v1
    spec:
      containers:
        - name: en-topic-settings
          image: eu.gcr.io/eve-notifications/en-topic-settings:latest
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: "20m"